library(gridExtra)
urlhead = 'http://www.exposomex.cn:8080/'

#' @title Initialize ExpoMeta Module
#' @description Initialize ExpoMeta module, the first step to start ExpoMeta Module.
#' @usage InitMeta()
#' @details ExpoMeta module mainly provides users preliminary information retrieval and screening for meta-analysis. Run InitMeta to get a unique PID for following steps.
#' @return An R6 class object.
#' @export
#' @examples res = InitMeta()
#' @author Weinan Lin, Bin Wang (corresponding author)

InitMeta = function(){
  url = paste0(urlhead,'InitMeta')
  seednum = sample(1000,1)
  res = httr::POST(url,
                   body = list(seednum = seednum),
                   encode = 'json')
  results = unserialize(httr::content(res))
  return(results$eSet)
}



#' @title Load Data for ExpoMeta Module
#' @description Upload local data file for ExpoMeta Module.
#' @usage LoadMeta(PID = NULL, Example = "default", DataPath = NULL)
#' @param PID chr. Program ID. It must be the same with the PID generated by InitMeta.
#' @param UseExample chr. A character indicates whether uses example data for analyses, available option include "example#1" for using example data1 and "default" for using data uploaded.
#' @param DataPath chr. Input file directory, e.g. "D:/test/eg_meta.xlsx". It should be
#'    noted that the slash symbol is "/", not "\".
#' @details After initializing ExpoMeta module, the second step is to upload local data file for ExpoMeta Module.
#'    Set param "UseExample = 'example#1'" to use example data1.
#'    LoadMeta can only run successfully after successfully running InitMeta.
#'    Please attention, PID must be got from the return result of InitMeta().
#' @return An R6 class object containing the input data.
#' @export
#' @examples res = InitMeta()
#'    res1 = LoadMeta(PID = res$PID,
#'    UseExample = "example#1",
#'    DataPath = NULL)
#' @author Weinan Lin, Bin Wang (corresponding author)

LoadMeta =function(PID = NULL,
                   UseExample = "default",
                   DataPath = NULL){
  url = paste0(urlhead,'LoadMeta')
  if(UseExample=="default"){
    exdata = readxl::read_excel(DataPath)

  }else{
    exdata = NULL}
  res = httr::POST(url,
                   body = serialize(list(PID=PID,
                                         UseExample=UseExample,
                                         Expodata=exdata),connection = NULL),
                   httr::content_type('application/x-rds'),
                   encode = 'raw')
  results = unserialize(httr::content(res))
  # results list
  return(results$eSet)
}


#' @title Search or Download Articles' Main Information
#' @description Search or download articles' main information based on keywords.
#' @usage MetaRefer(PID = NULL, Mode = "search", VarX = "default", VarY = "default", VarM = "default", YearFrom = "default", YearEnd = "default", PMID = "default", OutPath = "default")
#' @param PID chr. Program ID. It must be the same with the PID generated by InitMeta.
#' @param OutPath chr. Output file directory, e.g. "D:/output". If "default", the current working directory will be set. It should be noted that the slash symbol is "/", not "\".
#' @param Mode chr. Two modes are provided. “Search” for paper retrieval by keywords VarX/VarY/VarM/YearFrom/YearEnd, and “Download” for downloading main informain (main information only) for specified PMID.
#' @param VarX chr. “default” or a chemical names character (separate different values by ","). If “default”, the function will use the VarX values in the file loaded by LoadMeta. If a character (separate different values by ","), the function will use the chemical names in the character instead.
#' @param VarY chr. “default” or a disease names character (separate different values by ","). If “default”, the function will use the VarY values in the file loaded by LoadMeta. If a character (separate different values by ","), the function will use the disease names in the character instead.
#' @param VarM chr. “default” or a mediating factor names character (separate different values by ","). If “default”, the function will use the VarM values in the file loaded by LoadMeta. If a character (separate different values by ","), the function will use the mediating factor names in the character instead.
#' @param YearFrom chr. “default” or a disease names character (separate different values by ","). Limits the time range searched for "search" mode. If “default”, the function will use the YearFrom values in the file loaded by LoadMeta. If a character (separate different values by ","), the function will use the YearFrom in the character instead.
#' @param YearEnd chr. “default” or a disease names character (separate different values by ","). Limits the time range searched for "search" mode. If “default”, the function will use the YearEnd values in the file loaded by LoadMeta. If a character (separate different values by ","), the function will use the YearEnd in the character instead.
#' @param PMID chr. “default” or a disease names character (separate different values by ","). Refers to the papers PMID for "download" mode. If “default”, the function will use the PMID values in the file loaded by LoadMeta. If a character (separate different values by ","), the function will use the PMIDs in the character instead.
#' @details MetaRefer provides the functions of paper retrieval and relevance sorting, returning the information to the user based on keywords.
#'    Please attention, PID must be got from the return result of InitMeta().
#'    MetaRefer can only run successfully after successfully running InitMeta and LoadMeta functions.
#' @return A list object containing dataframe of articles' information.
#' @examples res = InitMeta()
#'    res1 = LoadMeta(PID = res$PID,
#'    UseExample = "example#1",
#'    DataPath = NULL)
#'    res2 = MetaRefer(PID = res$PID,
#'    OutPath = "default",
#'    Mode = "search",
#'    cVarX = "default",
#'    VarY = "default",
#'    VarM = "default",
#'    YearFrom = "default",
#'    YearEnd = "default",
#'    PMID = "default")
#' @author Weinan Lin, Bin Wang (corresponding author)

MetaRefer = function(PID = NULL,
                     OutPath = "default",
                     Mode = "search",
                     VarX = "default",
                     VarY = "default",
                     VarM = "default",
                     YearFrom = "default",
                     YearEnd = "default",
                     PMID = "default"){
  if(OutPath == 'default'){
    OutPath = getwd()
  }
  url = paste0(urlhead,'MetaRefer')
  res = httr::POST(url,
                   body = list(PID=PID,
                               MetaReferMode=Mode,
                               MetaVarX=VarX,
                               MetaVarY=VarY,
                               MetaVarM=VarM,
                               YearFrom=YearFrom,
                               YearEnd=YearEnd,
                               PMID=PMID),
                   encode = 'json')
  results = unserialize(httr::content(res))
  dir.create(paste0(OutPath,"/Refer"))
  for (name in names(results$MetaRefer_Papers$`Meta-analysis`)){
    try(writexl::write_xlsx(results$MetaRefer_Papers$`Meta-analysis`[[name]],
                            paste0(OutPath,"/Refer/",name,"[meta].xlsx")),silent = TRUE)
  }
  for (name in names(results$MetaRefer_Papers$SystematicReview)){
    try(writexl::write_xlsx(results$MetaRefer_Papers$SystematicReview[[name]],
                            paste0(OutPath,"/Refer/",name,"[systematic review].xlsx.xlsx")),silent = TRUE)
  }
  for (name in names(results$MetaRefer_Papers$OtherPapers)){
    try(writexl::write_xlsx(results$MetaRefer_Papers$OtherPapers[[name]],
                            paste0(OutPath,"/Refer/",name,".xlsx")),silent = TRUE)
  }
  try(writexl::write_xlsx(results$MetaRefer_Papers$All,
                            paste0(OutPath,"/Refer/All_Papers.xlsx")),silent = TRUE)
  return(results)
}



#' @title Visualize the Articles' Main Information
#' @description Visualize the articles' main information after MetaRefer function.
#' @usage VizRefer(PID = NULL, OutPath = "default")
#' @param PID chr. Program ID. It must be the same with the PID generated by InitMeta.
#' @param OutPath chr. Output file directory, e.g. "D:/output". If "default", the current working directory will be set. It should be noted that the slash symbol is "/", not "\".
#' @details VizRefer provides the visual function of articles' main information, showing the year and region distribution directly.
#'    Please attention, PID must be got from the return result of InitMeta().
#'    VizRefer can only run successfully after successfully running InitMeta, LoadMeta and MetaRefer functions.
#' @return A list object containing plots of article information visualization.
#' @export
#' @examples res = InitMeta()
#'    res1 = LoadMeta(PID = res$PID,
#'    UseExample = "example#1",
#'    DataPath = NULL)
#'    res2 = MetaRefer(PID = res$PID,
#'    OutPath = "default",
#'    Mode = "search",
#'    VarX = "default",
#'    VarY = "default",
#'    VarM = "default",
#'    YearFrom = "default",
#'    earEnd = "default",
#'    PMID = "default")
#'    res3 = VizRefer(PID=res$PID,
#'    OutPath = "default")
#' @author Weinan Lin, Bin Wang (corresponding author)

VizRefer = function(PID = NULL,
                    OutPath = "default"){
  if(OutPath == 'default'){
    OutPath = getwd()
  }
  url = paste0(urlhead,'VizRefer')
  res = httr::POST(url,
                   body = list(PID=PID),
                   encode = 'json')
  results = unserialize(httr::content(res))
  for (name in names(results$MetaRefer_Viz)){
    try(ggplot2::ggsave(paste0(OutPath,'/Refer/',name,".png"),
                        plot=results$MetaRefer_Viz[[name]],
                        width = 35,height = 15,units = "cm"),silent = TRUE)
  }
  return(results)
}



#' @title Review Relationship Between Exposure and Outcome
#' @description Review the relationship between exposure and outcome besed on chemical ID and disease ID.
#' @usage MetaReview(PID = NULL, CID = "default", DID = "default", OutPath = "default")
#' @param PID chr. Program ID. It must be the same with the PID generated by InitMeta.
#' @param OutPath chr. Output file directory, e.g. "D:/output". If "default", the current working directory will be set. It should be noted that the slash symbol is "/", not "\".
#' @param CID chr. “default” or a chemical ID character (separate different values by ","). If “default”, the function will use the Chemical_ID values in the file loaded by LoadMeta. If a character (separate different values by ","), the function will use the chemical ID in the character instead. Chemical_ID refers to the target chemical ID which can be inchikey (eg. JIAARYAFYJHUJI-UHFFFAOYSA-L ), cas.rn (eg. 7784-42-1) or our EXC ID (eg. EX:C01631).
#' @param DID chr. “default” or a disease ID character (separate different values by ","). If “default”, the function will use the Disease_ID values in the file loaded by LoadMeta. If a character (separate different values by ","), the function will use the disease ID in the character instead. Disease_ID refers to the target disease ID which can be MESH ID (format like MESH:D006973), OMIM ID (format like OMIM:182940) or our EXD ID (eg. EX:D16243)
#' @details MetaReview provides the functions of literature review. In the publishd papers, how many recorded that X is a protective/risky factor for Y? This questions can be solved by MetaReview function. (It can only search the papers available in our database)
#'    Please attention, PID must be got from the return result of InitMeta().
#'    MetaReview can only run successfully after successfully running InitMeta and LoadMeta functions.
#' @return A list object containing relationship visualization.
#' @export
#' @examples res = InitMeta()
#'    res1 = LoadMeta(PID = res$PID,
#'    UseExample = "example#1",
#'    DataPath = NULL)
#'    res2 = MetaReview(PID = res$PID,
#'    OutPath = "default",
#'    CID = "default",
#'    DID = "default")
#' @author Weinan Lin, Bin Wang (corresponding author)

MetaReview = function(PID = NULL,
                      CID = "default",
                      DID = "default",
                      OutPath = "default"){
  if(OutPath == 'default'){
    OutPath = getwd()
  }
  url = paste0(urlhead,'MetaReview')
  res = httr::POST(url,
                   body = list(PID=PID,
                               Chemical_ID=CID,
                               Disease_ID =DID),
                   encode = 'json')
  results = unserialize(httr::content(res))
  dir.create(paste0(OutPath,"/Review"))
  for (name in names(results$MetaReview_References)){
    try( writexl::write_xlsx(results$MetaReview_References[[name]],
                             paste0(OutPath,"/Review/",name,".xlsx")),silent = TRUE
    )
  }

  for (name in names(results$MetaReview_Plot)){
    try(ggplot2::ggsave(paste0(OutPath,'/Review/',name,'.jpg'),
                        plot = results$MetaReview_Plot[[name]],
                        width = 20,height = 15,units = "cm"),silent = TRUE)
  }
  return(results)
}



#' @title Pool Effect Value
#' @description Pool effect value in our meta database besed on chemical ID and disease ID.
#' @usage MetaEffect(PID = NULL, CID = "default", DID = "default", OutPath = "default")
#' @param PID chr. Program ID. It must be the same with the PID generated by InitMeta.
#' @param OutPath chr. Output file directory, e.g. "D:/output". If "default", the current working directory will be set. It should be noted that the slash symbol is "/", not "\".
#' @param CID chr. “default” or a chemical ID character (separate different values by ","). If “default”, the function will use the Chemical_ID values in the file loaded by LoadMeta. If a character (separate different values by ","), the function will use the chemical ID in the character instead. Chemical_ID refers to the target chemical ID which can be inchikey (eg. JIAARYAFYJHUJI-UHFFFAOYSA-L ), cas.rn (eg. 7784-42-1) or our EXC ID (eg. EX:C01631).
#' @param DID chr. “default” or a disease ID character (separate different values by ","). If “default”, the function will use the Disease_ID values in the file loaded by LoadMeta. If a character (separate different values by ","), the function will use the disease ID in the character instead. Disease_ID refers to the target disease ID which can be MESH ID (format like MESH:D006973), OMIM ID (format like OMIM:182940) or our EXD ID (eg. EX:D16243)
#' @details MetaEffect provides the functions of effect value pooling. In the publishd papers, what is the effect value between X and Y? This questions can be solved by MetaEffect function. It can provide the combined results of fixed effect model and random effect model. (It can only search the papers available in ExpoMeta database DB_Meta)
#'    Please attention, PID must be got from the return result of InitMeta().
#'    MetaEffect can only run successfully after successfully running InitMeta and LoadMeta functions.
#' @return A list object containing forest plots.
#' @export
#' @examples res = InitMeta()
#'    res1 = LoadMeta(PID = res$PID,
#'    UseExample = "example#1",
#'    DataPath = NULL)
#'    res2 = MetaEffect(PID=res$PID,
#'    OutPath = "default",
#'    CID = "default",
#'    DID = "default")
#' @author Weinan Lin, Bin Wang (corresponding author)

MetaEffect = function(PID = NULL,
                      OutPath = "default",
                      CID = "default",
                      DID = "default"){
  if(OutPath == 'default'){
    OutPath = getwd()
  }
  url = paste0(urlhead,'MetaEffect')
  res = httr::POST(url,
                   body = list(PID=PID,
                               Chemical_ID=CID,
                               Disease_ID=DID),
                   encode = 'json',
                   httr::timeout(600))
  results = unserialize(httr::content(res))

  dir.create(paste0(OutPath,"/Effect"))
  for (name in names(results$MetaEffect_References)){
    try( writexl::write_xlsx(results$MetaEffect_References[[name]],
                             paste0(OutPath,"/Effect/",name,".xlsx")),silent = TRUE
    )
  }

  for (name in names(results$MetaEffect_Plot)){
    png(file = paste0(OutPath,'/Effect/',name,".png"), width = 4000,
        height = 80*results$MetaEffect_Plotheight[[name]]+500, res = 300)
    results$MetaEffect_Plot[[name]]-> plot
    print(plot)
    dev.off()
  }
  return(results)
}

#' @title End the module analysis
#' @description End the module analysis
#' @usage FuncExit(PID)
#' @param PID chr. Program ID. It should be the same with the PID generated by InitBioLink.
#' @details
#' @return Exit status
#' @export
#' @examples res = InitMeta()
#'    res1 = LoadMeta(PID = res$PID,
#'    UseExample = "example#1",
#'    DataPath = NULL)
#'    res2 = MetaEffect(PID=res$PID,
#'    OutPath = "default",
#'    CID = "default",
#'    DID = "default")
#'    FuncExit(PID = res$PID)
#' @author Bin Wang (corresponding author)

FuncExit = function(PID){
  url = paste0(urlhead,'Exit')
  res = httr::POST(url,
                   body = list(PID=PID),
                   encode = 'json')
  if(res$status_code == 200){
    return("Success to exit. Thanks for using ExposomeX platform!")
  }else{
    return("No process needs exit. Thanks for using ExposomeX platform!")
  }
}
